In [33]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 100)

In [34]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [35]:
next(iter(data_iter))

[tensor([[-2.0669, -0.1234],
         [-1.0955, -2.1498],
         [-0.7441, -1.0654],
         [-1.5946, -1.2244],
         [-0.6904,  0.1325],
         [-0.0223, -2.6058],
         [ 0.1927,  1.0971],
         [-0.7378,  0.2652],
         [ 0.3546,  0.1974],
         [-1.0488, -0.1667]]),
 tensor([[ 0.4754],
         [ 9.3217],
         [ 6.3456],
         [ 5.1754],
         [ 2.3751],
         [13.0068],
         [ 0.8396],
         [ 1.8372],
         [ 4.2369],
         [ 2.6782]])]

In [5]:
for X, y in data_iter:
    print(X, y)
    break

tensor([[ 0.2810, -1.0202],
        [ 0.3287,  1.0641],
        [-0.2929, -0.1444],
        [ 0.2166,  0.1174],
        [ 1.1335, -0.0324],
        [ 0.0326, -0.3173],
        [ 0.4633,  0.1868],
        [ 0.0888, -0.6220],
        [-1.4894,  0.9906],
        [-1.9229,  1.0445]]) tensor([[ 8.2255],
        [ 1.2405],
        [ 4.1059],
        [ 4.2476],
        [ 6.5771],
        [ 5.3536],
        [ 4.4781],
        [ 6.4999],
        [-2.1455],
        [-3.1972]])


In [6]:
from torch import  nn

In [7]:
net = nn.Sequential(nn.Linear(2,1))

In [10]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [11]:
print(net[0].weight.data)

tensor([[0.0024, 0.0060]])


In [12]:
loss = nn.MSELoss()

In [13]:
y_true = torch.tensor([[3.0], [-0.5], [2.0], [8.0]])
y_true.shape

torch.Size([4, 1])

In [14]:
y_true.ndimension()

2

In [15]:
y_true = torch.tensor([3.0, -0.5, 2.0, 8.0])
y_true.shape

torch.Size([4])

In [16]:
trainer = torch.optim.SGD(net.parameters(), lr= 0.03)

In [18]:
num_epoch = 3
for epoch in range(num_epoch):
    for X, y in data_iter:
        prediction = net(X)
        trainer.zero_grad()
        l = loss(prediction, y)
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch{epoch + 1}, loss:{l:f}')

epoch1, loss:0.000102
epoch2, loss:0.000101
epoch3, loss:0.000101


In [19]:
from torch.utils.data import TensorDataset
features = torch.tensor([[1.0,2.0],[3.0,4.0], [5.0,6.0]])
labels = torch.tensor([[5.0],[11.0],[17.0]])

dataset = TensorDataset(features, labels)
dataset[0]

(tensor([1., 2.]), tensor([5.]))

In [20]:
from torch.utils.data import DataLoader

data_iter = DataLoader(dataset, batch_size = 2, shuffle = False)

for batch in data_iter:
    print(batch)

[tensor([[1., 2.],
        [3., 4.]]), tensor([[ 5.],
        [11.]])]
[tensor([[5., 6.]]), tensor([[17.]])]


In [23]:
for X, y in data_iter:
    print(f'X:{X}, y:{y}')

X:tensor([[1., 2.],
        [3., 4.]]), y:tensor([[ 5.],
        [11.]])
X:tensor([[5., 6.]]), y:tensor([[17.]])


In [37]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        print(f'X:{X}, y:{y}')
        l = loss(net(X), y)
        print(f'batch:{batch+1}, loss:{l:f}')
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

X:tensor([[-0.4143, -2.0576],
        [-0.4413,  0.0768],
        [ 0.0874,  0.7667],
        [ 1.3350, -1.3063],
        [-0.2990, -0.0916],
        [-2.2140, -0.7841],
        [-0.1595,  0.1486],
        [-1.0363, -0.5497],
        [-0.0818, -1.0107],
        [ 0.5074, -0.3701]]), y:tensor([[10.3537],
        [ 3.0645],
        [ 1.7549],
        [11.3221],
        [ 3.9260],
        [ 2.4388],
        [ 3.3786],
        [ 4.0075],
        [ 7.4682],
        [ 6.4846]])


TypeError: can only concatenate list (not "int") to list

In [42]:
num_epoch = 3

for epoch in range(num_epoch):
    for i, (X,y) in enumerate(data_iter):
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward
        trainer.step()

        if(i + 1) % 10 ==0:
            print(f'Epoch:{epoch + 1}, batch:{i + 1}, loss:{l:f}')

    l = loss(net(features), labels)
    print(f'Epoch:{epoch + 1}, overall loss: {l:f}')

Epoch:1, batch:10, loss:0.000076
Epoch:1, overall loss: 0.000078
Epoch:2, batch:10, loss:0.000136
Epoch:2, overall loss: 0.000078
Epoch:3, batch:10, loss:0.000067
Epoch:3, overall loss: 0.000078


In [43]:
true_w

tensor([ 2.0000, -3.4000])

In [45]:
w = net[0].weight.data
w

tensor([[ 1.9994, -3.3993]])

In [46]:
true_w.shape, w.shape

(torch.Size([2]), torch.Size([1, 2]))

In [47]:
t = w.reshape(true_w.shape)

In [48]:
t

tensor([ 1.9994, -3.3993])

In [49]:
print(f'w的误差是：{true_w - t}')

w的误差是：tensor([ 0.0006, -0.0007])


In [51]:
b = net[0].bias.data
print(f'b的误差是：{true_b - b}')

b的误差是：tensor([-0.0016])
